version: "3"
services:
  web:
    image: httpd:2.4.41
    container_name: web-httpd
    volumes:
      - "./webapp:/var/www/html"                                                                 
      - "./etc/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"                          
      - "./etc/apache2/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php

  php:
    build: ./php/
    container_name: app-php
    ports:
      - "10022:22"
    volumes:
      - "./webapp:/var/www/html"
    restart: always
#    depends_on:
#      - db

#  db:
#    image: mysql:5.7.26
#    container_name: ${MYSQL_HOST}                 
#    environment:                                  
#      - MYSQL_DATABASE=${MYSQL_DATABASE}          
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_USER=${MYSQL_USER}                  
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}          
#    volumes:                                      
#      - "./db/data:/var/lib/mysql"          
#      - "./db/dump:/docker-entrypoint-initdb.d"
#      - "./etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
#    ports:
#      - "3306:3306"
#    expose:                                       
#      - "3306"                                    
#    restart: always                               
